global:
  path: "dev"
  env: dev
  defaultValuesFile: values.yaml
  spec:
    project: default
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    source:
      repoURL:  https://github.com/amir-bialek/public
      targetRevision: HEAD

argocdApplications:
  github-runners:
    test:
      disableAutomated: false
      disableFinalizer: false
      disable: false
      name: test
      namespace: test
      disableServerSideApply: true
      wave: 9
      annotations: 
        argocd-image-updater.argoproj.io/image-list: myalias=docker.io/bialekamir/argocd-image-updater
        argocd-image-updater.argoproj.io/myalias.force-update: "true"