global:
  path: "dev"
  env: dev
  defaultValuesFile: values.yaml
  spec:
    project: default
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    source:
      repoURL:  https://github.com/amir-bialek/public
      targetRevision: HEAD

argocdApplications:
  github-runners:

    argocd-image-updater:
      disableAutomated: true
      disableFinalizer: false
      disable: false
      name: argocd-image-updater
      namespace: argocd
      disableServerSideApply: true
      wave: 9
      additionalValuesFiles:
        - values-add.yaml

    test:
      disableAutomated: true
      disableFinalizer: false
      disable: false
      name: test
      namespace: test
      disableServerSideApply: true
      wave: 9
      annotations: 
        argocd-image-updater.argoproj.io/image-list: ai=docker.io/bialekamir/argocd-image-updater
        argocd-image-updater.argoproj.io/ai.helm.image-tag: ai.deployment.image.tag
        argocd-image-updater.argoproj.io/ai.helm.image-name: ai.deployment.image.name
        # argocd-image-updater.argoproj.io/ai.update-strategy: digest
