global:
  path: "dev"
  env: dev
  defaultValuesFile: values.yaml
  spec:
    project: default
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    source:
      repoURL:  https://github.com/amir-bialek/public
      targetRevision: HEAD

argocdApplications:
  github-runners:
    test:
      disableAutomated: false
      disableFinalizer: false
      disable: false
      name: test
      namespace: test
      disableServerSideApply: false
      wave: 9
      annotations: 
        argocd-image-updater.argoproj.io/write-back-method: argocd 
        argocd-image-updater.argoproj.io/image-list: 'docker.io/bialekamir/argocd-image-updater:1.x.x'


    argocd-image-updater:
      disableAutomated: true
      disableFinalizer: false
      disable: false
      name: argocd-image-updater
      namespace: argocd
      disableServerSideApply: false
      wave: 8
      annotations: {}