global:
  path: "dev"
  env: dev
  defaultValuesFile: values.yaml
  spec:
    project: default
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    source:
      repoURL:  https://github.com/amir-bialek/public
      targetRevision: HEAD

argocdApplications:
  github-runners:
    test:
      disableAutomated: true
      disableFinalizer: false
      disable: false
      name: test
      namespace: test
      disableServerSideApply: true
      wave: 9

    loki-stack:
      disableAutomated: true
      disableFinalizer: false
      disable: false
      name: loki-stack
      namespace: monitoring
      disableServerSideApply: true
      wave: 9
      additionalValuesFiles:
        - values-add.yaml

    kube-prometheus-stack:
      disableAutomated: true
      disableFinalizer: false
      disable: false
      name: kube-prometheus-stack
      namespace: monitoring
      disableServerSideApply: true
      wave: 9
      additionalValuesFiles:
        - values-add.yaml

    artifactory-cpp-ce:
      disableAutomated: true
      disableFinalizer: false
      disable: false
      name: artifactory-cpp-ce
      namespace: default
      disableServerSideApply: true
      wave: 9
      additionalValuesFiles:
        - values-add.yaml